name: Deploy to Azure
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
    - name: Build image
      run: docker build -t ${{ steps.deploy.outputs.acrLoginServer }}/zero2prod .
    - name: Docker login
      run: az acr login -n ${{ steps.deploy.outputs.acrName }}
    - name: Push image
      run: docker push ${{ steps.deploy.outputs.acrLoginServer }}/zero2prod
